#!/usr/local/bin/php
<?php
$path = realpath(dirname(__FILE__));
chdir($path);
require_once 'Console/Bootstrap.php';

\Console\Bootstrap::bootStart(
        array($path)
);

try {
    $exitStatus = Console\Console::iniciar(basename(__FILE__), $argv );
    exit($exitStatus);
} catch (\Exception $e) {
    $tab = \Console\Config::get('tt_tab');
    $debug = \Console\Config::get('tt_debug');
    $msg = \Console\Color::strColor("Saida de procedimento: ", \Console\Color::FG_LIGHT_RED);
    \Console\Out::sysOutNl($msg);
    if($debug){
        echo "Message: " . $e->getMessage() . PHP_EOL;
        echo "File   : " . $e->getFile() . PHP_EOL;
        echo "Line   : " . $e->getLine() . PHP_EOL;
        echo str_repeat('=', 100) . "\n";
        echo "Message:" . PHP_EOL;
        echo $e->getTraceAsString() . PHP_EOL;
    } else {
        \Console\Out::sysErrNl($tab. $e->getMessage());
    }
    
    
    exit(1);
}